[env]
TERM = "xterm-256color"

[window.padding]
x = 10
y = 10


[font]
size = 12.0

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Never"

[selection]
save_to_clipboard = true

[colors.primary]
background = "0x2D2A2E"
foreground = "0xfff1f3"

[colors.normal]
black = "0x2c2525"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"

[colors.bright]
black = "0x72696a"
red = "0xfd6883"
green = "0xadda78"
yellow = "0xf9cc6c"
blue = "0xf38d70"
magenta = "0xa8a9eb"
cyan = "0x85dacc"
white = "0xfff1f3"
