[env]
TERM = "xterm-256color"

[window.padding]
x = 10
y = 10


[font]
size = 12.0

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "Never"

[selection]
save_to_clipboard = true

[general]
import = [
    "./themes/vague.toml"
]
